// TODO: move to util/constants
export const selectOptions = [
  { name: "CR: Fortos", value: "CR_Fortos", respawn: 300 },
  { name: "CR: Nogleth", value: "CR_Nogleth", respawn: 300 },
  { name: "CR: Renus", value: "CR_Renus", respawn: 300 },
  { name: "CR: Svac", value: "CR_Svac", respawn: 300 },
  { name: "NR: Bubbler", value: "NR_Bubbler", respawn: 300 },
  { name: "NR: Eldi", value: "NR_Eldi", respawn: 300 },
  { name: "NR: Lizentos", value: "NR_Lizentos", respawn: 300 },
  { name: "SR: Bubbler", value: "SR_Bubbler", respawn: 300 },
  { name: "SR: Dustyl", value: "SR_Dustyl", respawn: 300 },
  { name: "SR: Svaulon", value: "SR_Svaulon", respawn: 300 },
  { name: "WR: Fortos", value: "WR_Fortos", respawn: 300 },
  { name: "WR: Kelkundo", value: "WR_Kelkundo", respawn: 300 },
  { name: "RG: Ancient", value: "RG_Ancient", respawn: 900 },
  { name: "WK: Frostyl", value: "WK_Frostyl", respawn: 300 },
  { name: "WK: Bird", value: "WK_Bird", respawn: 300 },
  { name: "WK: Mammoth", value: "WK_Mammoth", respawn: 300 },
  { name: "SK: Yedi", value: "SK_Yedi", respawn: 300 },
  { name: "SK: Pangolan", value: "SK_Pangolan", respawn: 300 },
  { name: "CK: Banser", value: "CK_Banser", respawn: 300 },
  { name: "CK: Relyn", value: "CK_Relyn", respawn: 300 },
  { name: "NK: Bird", value: "NK_Bird", respawn: 300 },
];
