export const selectOptions = [
  // { name: "C: Fortos", value: "Central_Fortos" },
  // { name: "C: Nogleth", value: "Central_Nogleth" },
  // { name: "C: Renus", value: "Central_Renus" },
  // { name: "C: Svac", value: "Central_Svac" },
  // { name: "N: Bubbler", value: "North_Bubbler" },
  // { name: "N: Eldi", value: "North_Eldi" },
  // { name: "N: Lizentos", value: "North_Lizentos" },
  // { name: "S: Bubbler", value: "South_Bubbler" },
  // { name: "S: Dustyl", value: "South_Dustyl" },
  // { name: "S: Svaulon", value: "South_Svaulon" },
  // { name: "W: Fortos", value: "West_Fortos" },
  // { name: "W: Kelkundo", value: "West_Kelkundo" },

  { name: "RG: Ancient", value: "RG_Ancient" },
  { name: "WK: Frostyl", value: "WK_Frostyl" },
  { name: "WK: Mammoth", value: "WK_Mammoth" },
  { name: "SK: Yedi", value: "SK_Yedi" },
  { name: "WK: Bird", value: "WK_Bird" },
  { name: "CK: Banser", value: "CK_Banser" },
  { name: "CK: Relyn", value: "CK_Relyn" },
];
