// TODO: move to util/constants
export const selectOptions = [
  { name: "CR: Fortos", value: "CR_Fortos" },
  { name: "CR: Nogleth", value: "CR_Nogleth" },
  { name: "CR: Renus", value: "CR_Renus" },
  { name: "CR: Svac", value: "CR_Svac" },
  { name: "NR: Bubbler", value: "NR_Bubbler" },
  { name: "NR: Eldi", value: "NR_Eldi" },
  { name: "NR: Lizentos", value: "NR_Lizentos" },
  { name: "SR: Bubbler", value: "SR_Bubbler" },
  { name: "SR: Dustyl", value: "SR_Dustyl" },
  { name: "SR: Svaulon", value: "SR_Svaulon" },
  { name: "WR: Fortos", value: "WR_Fortos" },
  { name: "WR: Kelkundo", value: "WR_Kelkundo" },
  { name: "RG: Ancient", value: "RG_Ancient" },
  { name: "WK: Frostyl", value: "WK_Frostyl" },
  { name: "WK: Bird", value: "WK_Bird" },
  { name: "WK: Mammoth", value: "WK_Mammoth" },
  { name: "SK: Yedi", value: "SK_Yedi" },
  { name: "SK: Pangolan", value: "SK_Pangolan" },
  { name: "CK: Banser", value: "CK_Banser" },
  { name: "CK: Relyn", value: "CK_Relyn" },
];
